import type { Metadata } from "next";
import "./globals.css";
import { DownloadProvider } from "@/Components/DownloadContext";
import SearchPage from "@/Components/SearchPage";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    modal
}: Readonly<{
    children: React.ReactNode;
    modal: React.ReactNode;
}>) {
    return (
        <html lang="zh">
            <body
                className={` antialiased overflow-hidden`}
            >
                <DownloadProvider>
                    <div
                        className="absolute inset-0 bg-cover bg-center blur-sm"
                        style={{ backgroundImage: "url('bg.png')" }}
                    />
                    
                    <div className="absolute inset-0 border-4 border-red-600">
                        {modal}
                        <SearchPage />
                    </div>

                    <div className="absolute inset-0 pointer-events-none flex items-start justify-center border-4 border-black">

                        {children}
                    </div>
                </DownloadProvider>
            </body>
        </html>
    );
}
